#!/bin/bash

SIMULATOR=$1

input_dir="tb/test_cases"
out_dir="test/temp"

for F in ${input_dir}/*.txt
do
    # extract file name
    base=$(echo $F | sed -E -e "s|${input_dir}/([^.]+)[.]txt|\1|g");

    # run parser on text file and obtain binary output
    mips-parser/bin/parser ${input_dir}/${base}.txt ${out_dir}/${base}.bin &>/dev/null

    # store commented test information at top of txt file
    line3=$(sed -n '3p' ${input_dir}/${base}.txt)
    result_str=${line3:1}
    printf -v int '%d\n' "$result_str" 2>/dev/null

    # run simulator
    ${SIMULATOR} ${out_dir}/${base}.bin

    # store output 
    output=$?

    # check for pass/fail
    if [[ ${output} -eq ${int} ]] ; then
	echo "${base}, pass, "
    else
	echo "${base}, fail, expected ${int}, got ${output}"
    fi
    line5=$(sed -n '5p' ${input_dir}/${base}.txt)
    echo "Explanation of ${base}: ${line5:1}"
done

echo -e "Finished.\n"

